listener 1883 0.0.0.0
protocol mqtt
max_connections 100

allow_anonymous true

persistence true
persistence_location /Users/batagota/BATAGOTA/10_AI_BATA/02_BATA_MQTT/data/
autosave_interval 180

connection_messages true
log_timestamp true
log_type error
log_type warning
log_type notice
log_type information
log_dest file /Users/batagota/BATAGOTA/10_AI_BATA/02_BATA_MQTT/logs/mosquitto.log
