"""
BATAGOTA Core Agent - 진입점
Claude API 기반 AI 에이전트
"""
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from dotenv import load_dotenv
from core.agent.org_hierarchy import ManagerAgent

# 마스터 폴더를 sys.path에 추가
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

# 환경변수 로드
load_dotenv(Path(__file__).parent.parent.parent / "config" / ".env")

# 라우팅 규칙 로드
with open(Path(__file__).parent.parent.parent / "config" / "routing.json", "r", encoding="utf-8") as f:
    ROUTING = json.load(f)

MANAGER_AGENT = ManagerAgent(ROUTING["routing"])


def route_intent(intent: str, params: dict = None, auto_upload: bool = True) -> dict:
    """
    Intent 기반 요청 라우팅
    
    Args:
        intent: 실행할 의도 (intent 이름)
        params: 파라미터 딕셔너리
        auto_upload: 생성 파일 자동 Google Drive 업로드 여부
    
    Returns:
        {
            status: "success" | "error",
            intent: str,
            result: dict,
            output_file: str (파일 생성 시),
            drive_link: str (업로드 시)
        }
    """
    if params is None:
        params = {}
    
    if intent not in ROUTING["routing"]:
        return {"status": "error", "error": f"Unknown intent: {intent}"}

    route = ROUTING["routing"][intent]
    project = route["project"]
    
    try:
        execution = MANAGER_AGENT.execute_task(intent=intent, params=params)
        
        # Output 처리
        response = {
            "status": execution.get("status", "error"),
            "intent": intent,
            "result": execution.get("result", {})
        }

        if execution.get("org_trace"):
            response["org_trace"] = execution.get("org_trace")
        if execution.get("error") and response["status"] == "error":
            response["error"] = execution.get("error")

        if execution.get("output_file"):
            response["output_file"] = execution.get("output_file")
        if execution.get("output_type"):
            response["output_type"] = execution.get("output_type")
        
        # 파일 생성 시 Google Drive 업로드
        if auto_upload and response.get("output_file"):
            file_path = response.get("output_file")
            agent_name = project.replace("/", "_")  # 02_BATA_MQTT -> 02_BATA_MQTT
            credentials_path = os.getenv("GOOGLE_CREDENTIALS_PATH") or os.getenv("GDRIVE_CREDENTIALS_JSON")
            token_path = os.getenv("GOOGLE_TOKEN_PATH") or os.getenv("GDRIVE_TOKEN_JSON")
            
            try:
                sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent / "02_BATA_MQTT"))
                from gdrive_file_upload import upload_file_to_gdrive
                
                upload_kwargs = {
                    "file_path": file_path,
                    "agent_name": agent_name,
                    "file_type": response.get("output_type"),
                    "metadata": {
                        "description": f"Generated by {intent} at {datetime.now(timezone.utc).isoformat()}"
                    },
                }
                if credentials_path:
                    upload_kwargs["credentials_path"] = credentials_path
                if token_path:
                    upload_kwargs["token_path"] = token_path

                upload_result = upload_file_to_gdrive(**upload_kwargs)
                
                if upload_result.get("status") == "success":
                    response["drive_link"] = upload_result.get("file_link")
                    response["file_id"] = upload_result.get("file_id")
                else:
                    response["drive_upload_error"] = upload_result.get("error", "Drive upload failed")
            except Exception as e:
                response["drive_upload_error"] = str(e)
        
        return response
        
    except Exception as e:
        return {"status": "error", "error": str(e), "intent": intent}


def main():
    """CLI 모드로 에이전트 실행"""
    print("=" * 50)
    print("  BATAGOTA AI Agent")
    print("  Claude API 기반 프로젝트 관리 에이전트")
    print("=" * 50)
    print()
    print("Available intents:")
    for intent in ROUTING["routing"].keys():
        print(f"  - {intent}")
    print()
    print("Example: mqtt_report")
    result = route_intent("mqtt_report")
    print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
