pid=BATAGOTA
listener
{
    port 1883
    protocol mqtt
}

# WebSocket (선택)
# listener 9001
# protocol websockets

log_type all
log_dest file /mosquitto/log/mosquitto.log

persistence true
persistence_location /mosquitto/data/

# 인증 (Phase 2에서 설정)
# password_file /mosquitto/config/passwd
# allow_anonymous false
allow_anonymous true
